# Question 2 - Perceptron

In this problem, we need to build a perceptron to classify the images.

In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
%matplotlib inline

## Preparing the data

We use the data that we processed and saved in csv files during Question 1. The data is read and separated into training data and testing data in order to be fitted into the perceptron model.

In [2]:
train_dataframe = pd.read_csv('../dataset/train_data.csv', index_col =0)
test_dataframe = pd.read_csv('../dataset/test_data.csv', index_col =0)

In [3]:
train_dataframe.head()

,0,1,2,3,4,5,6,7,8,9,...,1791,1792,1793,1794,1795,1796,1797,1798,1799,class
0,166.000000,163.000000,165.333333,155.333333,147.666667,164.666667,154.000000,155.000000,140.000000,140.000000,...,26.000000,27.555556,18.666667,18.000000,21.555556,42.666667,42.888889,21.555556,72.000000,0
1,149.333333,148.000000,141.333333,148.666667,133.000000,129.333333,104.000000,42.333333,171.666667,152.666667,...,142.888889,166.888889,181.555556,162.888889,108.666667,97.555556,60.666667,72.666667,108.666667,0
2,56.333333,43.000000,71.000000,71.333333,66.666667,67.000000,81.000000,61.333333,76.000000,90.333333,...,0.888889,10.888889,44.222222,40.222222,18.000000,20.222222,26.000000,34.888889,29.555556,0
3,87.666667,90.666667,94.000000,99.000000,115.000000,109.000000,145.666667,146.000000,85.333333,92.333333,...,270.222222,190.888889,13.555556,90.888889,90.888889,118.222222,504.000000,416.222222,469.555556,1
4,23.333333,22.333333,22.333333,21.333333,21.000000,23.000000,20.000000,20.333333,21.000000,25.000000,...,10.888889,20.666667,8.222222,4.666667,4.666667,4.666667,14.222222,14.222222,0.888889,0

In [4]:
test_dataframe.head()

,0,1,2,3,4,5,6,7,8,9,...,1791,1792,1793,1794,1795,1796,1797,1798,1799,class
0,60.333333,85.000000,110.666667,90.000000,30.333333,36.333333,72.000000,82.666667,91.000000,80.666667,...,174.888889,131.555556,54.888889,98.000000,37.555556,113.555556,94.888889,116.666667,49.555556,1
1,151.666667,139.000000,154.666667,172.333333,141.666667,146.666667,166.333333,174.333333,167.000000,168.333333,...,402.000000,724.222222,818.000000,901.555556,637.555556,0.888889,4.666667,1.555556,4.666667,1
2,64.666667,83.666667,95.000000,89.666667,96.000000,80.000000,72.666667,58.000000,66.000000,91.666667,...,8.000000,2.888889,1.555556,1.555556,1.555556,2.666667,0.888889,4.666667,16.888889,0
3,156.333333,108.000000,151.333333,150.333333,153.666667,150.333333,99.333333,145.333333,152.333333,153.333333,...,168.222222,8.222222,8.222222,12.666667,4.666667,1.555556,6.888889,9.555556,0.888889,0
4,229.000000,235.000000,252.666667,231.000000,233.333333,232.333333,230.333333,229.333333,229.333333,199.000000,...,62.000000,62.000000,62.000000,62.000000,62.000000,62.000000,54.888889,40.222222,32.000000,0

In [5]:
X_train = train_dataframe.drop(['class'], axis=1).values
y_train = train_dataframe['class'].to_numpy()

X_test = test_dataframe.drop(['class'], axis=1).values
y_test = test_dataframe['class'].to_numpy()

X_train.shape, y_train.shape, X_test.shape, y_test.shape

((100, 1800), (100,), (20, 1800), (20,))

## Building the Perceptron class

In [8]:
class Perceptron():
    
    # Constructor
    def __init__(self, size, epochs = 10000, lr = 1):
        self.w = np.zeros(size + 1)
        self.b = 0
        self.epochs = epochs
        self.lr = lr    
    
    #model
    def model(self, x):
        return 1 if x>= 0.5 else 0
    
     # Creating a predict function 
    def predict(self, X):
        preds = []
        for i in range(X.shape[0]):
            x = np.insert(X[i], 0, 1)
            y = self.get_predictions(x)
            preds.append(y)
        
        return np.array(preds)
    
     # Creating a prediction function which will take input features and returns 1 or 0
    def get_predictions(self, x):
        z = np.dot(self.w.T, x)
        a = self.model(z)
        return a
    
    # Creating a training function which keeps the error to a minimum
    def fit(self, X, labels):
        for e in range(self.epochs):
            for i in range(X.shape[0]):
                x = np.insert(X[i], 0, 1)
                y = self.get_predictions(x)
                error = labels[i] - y
                self.w = self.w + (self.lr * error * x)

In the above class, we first create the constructor which initializes the weights and the bias, epochs and the learning rate. The function model is the activation function takes input values x as an argument and returns 1 for positive outputs else 0.

Next, we have the predict function that takes input values x as an argument and for every observation present in x, the function calculates the predicted outcome and returns a list of predictions.

Finally, we will implement fit function to learn the best possible weight vector w and threshold value b for the given data.

## Training and testing the perceptron

In [10]:
# Training using training data
perceptron = Perceptron(size= X_train.shape[1])
perceptron.fit(X_train, y_train)

# Testing using test data
perceptron_predictions = perceptron.predict(X_test)
print("Real labels: ",y_test)
print("Predicted labels",perceptron_predictions)
print("Accuracy:", accuracy_score(y_true=y_test, y_pred=perceptron_predictions))

Real labels:  [1 1 0 0 0 0 0 1 0 1 1 1 1 1 1 0 1 1 0 1]
Predicted labels [1 1 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0]
Accuracy: 0.5

## Varying the learning rate

In [11]:
learning_rate = 0.01

# Training using training data
perceptron = Perceptron(size= X_train.shape[1], lr = learning_rate)
perceptron.fit(X_train, y_train)

# Testing using test data
perceptron_predictions = perceptron.predict(X_test)
print("Real labels: ",y_test)
print("Predicted labels",perceptron_predictions)
print("Accuracy:", accuracy_score(y_true=y_test, y_pred=perceptron_predictions))

Real labels:  [1 1 0 0 0 0 0 1 0 1 1 1 1 1 1 0 1 1 0 1]
Predicted labels [1 1 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0]
Accuracy: 0.5

In [12]:
learning_rate = 0.1

# Training using training data
perceptron = Perceptron(size= X_train.shape[1], lr = learning_rate)
perceptron.fit(X_train, y_train)

# Testing using test data
perceptron_predictions = perceptron.predict(X_test)
print("Real labels: ",y_test)
print("Predicted labels",perceptron_predictions)
print("Accuracy:", accuracy_score(y_true=y_test, y_pred=perceptron_predictions))

Real labels:  [1 1 0 0 0 0 0 1 0 1 1 1 1 1 1 0 1 1 0 1]
Predicted labels [1 1 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0]
Accuracy: 0.5

In [13]:
learning_rate = 1

# Training using training data
perceptron = Perceptron(size= X_train.shape[1], lr = learning_rate)
perceptron.fit(X_train, y_train)

# Testing using test data
perceptron_predictions = perceptron.predict(X_test)
print("Real labels: ",y_test)
print("Predicted labels",perceptron_predictions)
print("Accuracy:", accuracy_score(y_true=y_test, y_pred=perceptron_predictions))

Real labels:  [1 1 0 0 0 0 0 1 0 1 1 1 1 1 1 0 1 1 0 1]
Predicted labels [1 1 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0]
Accuracy: 0.5